[package]
name = "logical_universe"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.19"
env_logger = "0.10"
pollster = "0.3"
image = "0.24"
bytemuck = { version = "1.4", features = ["derive"] }
imageproc = "0.23"
rusttype = "0.9"
ab_glyph = "0.2"
clap = { version = "4.0", features = ["derive"] }
