import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  build: {
    rollupOptions: {
      output: {
        manualChunks: undefined,
        entryFileNames: 'assets/nand_adder.js', // Renames the main JS bundle
        chunkFileNames: 'assets/[name].js',
        assetFileNames: (assetInfo) => {
          // Check if it's the main CSS file generated by cssCodeSplit: false
          if (assetInfo.name === 'style.css') { // Default name when cssCodeSplit: false
            return 'assets/nand_adder.css';
          }
          return 'assets/[name].[ext]'; // For other assets
        },
      }
    },
    cssCodeSplit: false,
    assetsInlineLimit: 100000000,
  }
})
