use physics_sim::fields::{FieldCoupling, FieldType};
use physics_sim::particles::{Particle, Atom};
use physics_sim::elements::{Element, MaterialDef};
use physics_sim::benchmark::GoldStandard;
use physics_sim::visualization::SimulationVisualizer;
use rand::Rng;

// Simulation Parameters
const SIM_WIDTH: u32 = 800;
const SIM_HEIGHT: u32 = 200;
const ATOM_DENSITY: f64 = 0.1;
const PHOTON_COUNT: usize = 500;

// Doping Configuration
// N-Type Side (Left)
const N_DOPANT: Element = Element::Phosphorus;
const N_DOPING_CONCENTRATION: f64 = 0.001; // 1 in 1000 atoms
// P-Type Side (Right)
const P_DOPANT: Element = Element::Boron;
const P_DOPING_CONCENTRATION: f64 = 0.001;

fn main() {
    // Choose your host material here
    let host_material = MaterialDef::silicon(); // Or MaterialDef::gallium_arsenide();
    let host_element = host_material.elements[0].0; // Assuming primary element is the host

    println!("Initializing 2D Simulation with Doped Lattice...");
    println!("Host: {}, N-Type: {:?}, P-Type: {:?}", host_material.name, N_DOPANT, P_DOPANT);
    
    let universe_constants = FieldCoupling::electrodynamics_only();
    let mut visualizer = SimulationVisualizer::new(SIM_WIDTH, SIM_HEIGHT);
    
    let band_gap_ev = host_material.band_gap;


    // 1. Setup Material Lattice
    // We build the lattice atom by atom, applying doping logic.
    let mut atoms = Vec::new();
    
    // Track carriers generated by doping (Thermally ionized at room temp)
    let mut carriers: Vec<Particle> = Vec::new();

    for x in 200..600 {
        for y in 0..SIM_HEIGHT {
            if rand::rng().random::<f64>() < ATOM_DENSITY {
                // Determine Element Type
                let element = if x < 400 {
                    // N-Side
                    if rand::rng().random::<f64>() < N_DOPING_CONCENTRATION {
                        N_DOPANT // Doped!
                    } else {
                        host_element
                    }
                } else {
                    // P-Side
                    if rand::rng().random::<f64>() < P_DOPING_CONCENTRATION {
                        P_DOPANT // Doped!
                    } else {
                        host_element
                    }
                };

                let atom = Atom::new(element, x as f64, y as f64, 0.0);
                
                // Visualization color coding? 
                visualizer.draw_atom(x as f64, y as f64);
                
                // Doping Physics: Create Free Carriers
                if element.valence_electrons() > host_element.valence_electrons() {
                    let excess = element.valence_electrons() - host_element.valence_electrons();
                    for _ in 0..excess {
                        carriers.push(Particle::new_charge_carrier(FieldType::FreeElectron, x as f64, y as f64));
                    }
                }
                else if element.valence_electrons() < host_element.valence_electrons() {
                     let deficit = host_element.valence_electrons() - element.valence_electrons();
                     for _ in 0..deficit {
                        carriers.push(Particle::new_charge_carrier(FieldType::Hole, x as f64, y as f64));
                     }
                }

                atoms.push(atom);
            }
        }
    }
    println!("Created Lattice with {} atoms.", atoms.len());
    println!("Doping generated {} intrinsic carriers (Free Electrons/Holes).", carriers.len());

    // 2. Run Photon Simulation (Generation)
    let mut absorbed_count = 0;
    let mut active_photons = 0;
    let mut survival_counts: Vec<i32> = vec![0; SIM_WIDTH as usize];

    println!("Firing {} photons...", PHOTON_COUNT);

    for _ in 0..PHOTON_COUNT {
        let start_y = rand::rng().random_range(0.0..SIM_HEIGHT as f64);
        let mut photon = Particle::new_photon(2.5, 0.0, start_y, 0.0); // Green light
        let mut path = Vec::new();
        let mut is_absorbed = false;

        while photon.position.x < SIM_WIDTH as f64 {
            path.push((photon.position.x, photon.position.y));
            
            // Record survival
            let px_idx = photon.position.x as usize;
            if px_idx < survival_counts.len() {
                survival_counts[px_idx] += 1;
            }

            photon.position.x += 1.0;

            // Interaction Check (Inside slab)
            if photon.position.x >= 200.0 && photon.position.x < 600.0 {
                let prob = ATOM_DENSITY * universe_constants.electromagnetic * 10.0;
                
                if rand::rng().random::<f64>() < prob {
                     if photon.energy >= band_gap_ev {
                        is_absorbed = true;
                        visualizer.draw_absorption(photon.position.x, photon.position.y);
                        
                        // Photogeneration: Create NEW Electron-Hole Pair
                        carriers.push(Particle::new_charge_carrier(FieldType::FreeElectron, photon.position.x, photon.position.y));
                        carriers.push(Particle::new_charge_carrier(FieldType::Hole, photon.position.x, photon.position.y));
                        
                        break;
                     }
                }
            }
        }

        if !is_absorbed {
            active_photons += 1;
        } else {
            absorbed_count += 1;
        }
        
        if rand::rng().random::<f64>() < 0.1 {
            visualizer.draw_photon_path(&path);
        }
    }

    // 3. Simulate Current (Drift + Diffusion)
    println!("Simulating Carrier Transport ({} total carriers)...", carriers.len());
    
    for _tick in 0..100 {
        for carrier in carriers.iter_mut() {
            if !carrier.active { continue; }
            
            let dist_from_junction = (carrier.position.x - 400.0).abs();
            let field_strength = if dist_from_junction < 50.0 {
                0.8 * (-dist_from_junction / 20.0).exp()
            } else {
                0.0
            };
            
            let force_x = carrier.charge * field_strength;
            
            carrier.position.x += force_x;
            
            let noise = (rand::rng().random::<f64>() - 0.5) * 0.5;
            carrier.position.x += noise;

            visualizer.draw_carrier(carrier.position.x, carrier.position.y, carrier.kind == FieldType::Hole);

            if carrier.kind == FieldType::FreeElectron && carrier.position.x <= 200.0 {
                carrier.active = false;
            } else if carrier.kind == FieldType::Hole && carrier.position.x >= 600.0 {
                carrier.active = false;
            }
        }
    }

    println!("Simulation Complete.");
    visualizer.save("simulation_output.png");
    println!("Saved visual to 'simulation_output.png'");

    // 4. Verify against Gold Standard
    let sim_data: Vec<(f64, f64)> = survival_counts.iter().enumerate()
        .filter(|(x, _)| *x >= 200 && *x < 600) // Only measure inside the slab
        .step_by(10) // Sample every 10 pixels
        .map(|(x, count)| ((x - 200) as f64, *count as f64)) // Shift x relative to slab start
        .collect();

    let theory_sigma = universe_constants.electromagnetic * 10.0;
    let initial_slab_count = survival_counts[200] as f64;

    match GoldStandard::generate_attenuation_plot(
        "benchmark_plot.png", 
        &sim_data, 
        ATOM_DENSITY, 
        theory_sigma,
        initial_slab_count
    ) {
        Ok(_) => println!("Saved benchmark plot to 'benchmark_plot.png'"),
        Err(e) => println!("Failed to generate plot: {}", e),
    }

    // --- Efficiency Calculation ---
    // Output Current (Collected carriers)
    let collected_electrons = carriers.iter().filter(|c| !c.active && c.kind == FieldType::FreeElectron).count() as f64;
    let collected_holes = carriers.iter().filter(|c| !c.active && c.kind == FieldType::Hole).count() as f64;
    
    // Total collected electron-hole pairs that contributed to current
    let effective_collected_pairs = collected_electrons.min(collected_holes);

    // Ideal Open Circuit Voltage (Voc) - Simplified approximation
    let estimated_voc = band_gap_ev * 0.7; // Volts, simple heuristic

    // Input Light Energy (in eV)
    let total_input_photon_energy_ev = PHOTON_COUNT as f64 * 2.5; // Each photon was 2.5 eV

    // Output electrical energy in eV-Volts (effectively a power proxy here)
    // To get actual energy in Joules, we'd multiply by elementary charge 'e'
    let output_energy_proxy_ev = effective_collected_pairs * estimated_voc; 
    
    let efficiency = (output_energy_proxy_ev / total_input_photon_energy_ev) * 100.0;

    println!("--------------------------------------------------");
    println!("Efficiency Results for {}:", host_material.name);
    println!("  Material Band Gap: {:.2} eV", band_gap_ev);
    println!("  Estimated Voc: {:.2} V", estimated_voc);
    println!("  Photons Fired: {}", PHOTON_COUNT);
    println!("  Collected Electron-Hole Pairs: {:.0}", effective_collected_pairs);
    println!("  Total Input Photon Energy: {:.0} eV", total_input_photon_energy_ev);
    println!("  Effective Output Energy (proxy): {:.0} eV*V", output_energy_proxy_ev);
    println!("  Power Conversion Efficiency: {:.2}%", efficiency);
    println!("--------------------------------------------------");
}
