use physics_sim::fields::{FieldCoupling, FieldType};
use physics_sim::particles::{Particle, Atom};
use physics_sim::elements::Element;
use physics_sim::benchmark::GoldStandard;
use physics_sim::visualization::SimulationVisualizer;
use rand::Rng;

// Simulation Parameters
const SIM_WIDTH: u32 = 800;
const SIM_HEIGHT: u32 = 200;
const ATOM_DENSITY: f64 = 0.1;
const PHOTON_COUNT: usize = 500;

// Doping Configuration
const HOST_ELEMENT: Element = Element::Silicon;
// N-Type Side (Left)
const N_DOPANT: Element = Element::Phosphorus;
const N_DOPING_CONCENTRATION: f64 = 0.001; // 1 in 1000 atoms
// P-Type Side (Right)
const P_DOPANT: Element = Element::Boron;
const P_DOPING_CONCENTRATION: f64 = 0.001;

fn main() {
    println!("Initializing 2D Simulation with Doped Lattice...");
    println!("Host: {:?}, N-Type: {:?}, P-Type: {:?}", HOST_ELEMENT, N_DOPANT, P_DOPANT);
    
    let universe_constants = FieldCoupling::electrodynamics_only();
    let mut visualizer = SimulationVisualizer::new(SIM_WIDTH, SIM_HEIGHT);
    
    // Band Gap Map (spatially varying)
    // We will define the junction at x=400
    // Left side (200-400): N-doped
    // Right side (400-600): P-doped
    // Band gap is mostly determined by the host (Si ~ 1.1 eV), 
    // but strictly speaking, doping narrows it slightly. We'll stick to 1.1 eV for now.
    let band_gap_ev = 1.1;

    // 1. Setup Material Lattice
    // We build the lattice atom by atom, applying doping logic.
    let mut atoms = Vec::new();
    
    // Track carriers generated by doping (Thermally ionized at room temp)
    let mut carriers: Vec<Particle> = Vec::new();

    for x in 200..600 {
        for y in 0..SIM_HEIGHT {
            if rand::rng().random::<f64>() < ATOM_DENSITY {
                // Determine Element Type
                let element = if x < 400 {
                    // N-Side
                    if rand::rng().random::<f64>() < N_DOPING_CONCENTRATION {
                        N_DOPANT // Doped!
                    } else {
                        HOST_ELEMENT
                    }
                } else {
                    // P-Side
                    if rand::rng().random::<f64>() < P_DOPING_CONCENTRATION {
                        P_DOPANT // Doped!
                    } else {
                        HOST_ELEMENT
                    }
                };

                let atom = Atom::new(element, x as f64, y as f64, 0.0);
                
                // Visualization color coding? 
                // We can't change the visualizer signature easily, but let's just draw atoms.
                visualizer.draw_atom(x as f64, y as f64); // Maybe add color support later
                
                // Doping Physics: Create Free Carriers
                // If we placed a Phosphorous (5 valence) in Silicon (4 valence):
                // 5 - 4 = +1 Free Electron.
                if element.valence_electrons() > HOST_ELEMENT.valence_electrons() {
                    let excess = element.valence_electrons() - HOST_ELEMENT.valence_electrons();
                    for _ in 0..excess {
                        carriers.push(Particle::new_charge_carrier(FieldType::FreeElectron, x as f64, y as f64));
                    }
                }
                // If we placed Boron (3 valence) in Silicon (4 valence):
                // 4 - 3 = 1 Missing Electron (Hole).
                else if element.valence_electrons() < HOST_ELEMENT.valence_electrons() {
                     let deficit = HOST_ELEMENT.valence_electrons() - element.valence_electrons();
                     for _ in 0..deficit {
                        carriers.push(Particle::new_charge_carrier(FieldType::Hole, x as f64, y as f64));
                     }
                }

                atoms.push(atom);
            }
        }
    }
    println!("Created Lattice with {} atoms.", atoms.len());
    println!("Doping generated {} intrinsic carriers (Free Electrons/Holes).", carriers.len());

    // 2. Run Photon Simulation (Generation)
    let mut absorbed_count = 0;
    let mut active_photons = 0;
    let mut survival_counts: Vec<i32> = vec![0; SIM_WIDTH as usize];

    println!("Firing {} photons...", PHOTON_COUNT);

    for _ in 0..PHOTON_COUNT {
        let start_y = rand::rng().random_range(0.0..SIM_HEIGHT as f64);
        let mut photon = Particle::new_photon(2.5, 0.0, start_y, 0.0); // Green light
        let mut path = Vec::new();
        let mut is_absorbed = false;

        while photon.position.x < SIM_WIDTH as f64 {
            path.push((photon.position.x, photon.position.y));
            
            // Record survival
            let px_idx = photon.position.x as usize;
            if px_idx < survival_counts.len() {
                survival_counts[px_idx] += 1;
            }

            photon.position.x += 1.0;

            // Interaction Check (Inside slab)
            if photon.position.x >= 200.0 && photon.position.x < 600.0 {
                let prob = ATOM_DENSITY * universe_constants.electromagnetic * 10.0;
                
                if rand::rng().random::<f64>() < prob {
                     if photon.energy >= band_gap_ev {
                        is_absorbed = true;
                        visualizer.draw_absorption(photon.position.x, photon.position.y);
                        
                        // Photogeneration: Create NEW Electron-Hole Pair
                        carriers.push(Particle::new_charge_carrier(FieldType::FreeElectron, photon.position.x, photon.position.y));
                        carriers.push(Particle::new_charge_carrier(FieldType::Hole, photon.position.x, photon.position.y));
                        
                        break;
                     }
                }
            }
        }

        if !is_absorbed {
            active_photons += 1;
        } else {
            absorbed_count += 1;
        }
        
        if rand::rng().random::<f64>() < 0.1 {
            visualizer.draw_photon_path(&path);
        }
    }

    // 3. Simulate Current (Drift + Diffusion)
    // In a real P-N junction, the carriers diffuse until they create an E-field.
    // For this "Toy" model, we will apply a logic:
    // "If there are more Electrons on the Left (N-type), they want to diffuse Right."
    // "If there are more Holes on the Right (P-type), they want to diffuse Left."
    // BUT, the built-in E-field (from the initial diffusion) stops them.
    // 
    // The *Photogenerated* carriers are the ones that generate useful current.
    // The Field points N -> P (Left -> Right) ??? 
    // Wait, N-side has (+) ions left behind. P-side has (-) ions left behind.
    // Field points (+) -> (-), so N -> P (Left -> Right).
    // Electron (negative) moves AGAINST field -> Moves Left (out of N terminal).
    // Hole (positive) moves WITH field -> Moves Right (out of P terminal).
    
    // We will stick to the "Simple Field" logic for drift, but now applied to the 
    // new mixed carrier population.
    
    println!("Simulating Carrier Transport ({} total carriers)...", carriers.len());
    
    for _tick in 0..100 {
        for carrier in carriers.iter_mut() {
            if !carrier.active { continue; }
            
            // Field exists mainly at the junction (x=400).
            // Let's model a Gaussian field around x=400.
            let dist_from_junction = (carrier.position.x - 400.0).abs();
            let field_strength = if dist_from_junction < 50.0 {
                // Strong field near junction
                0.8 * (-dist_from_junction / 20.0).exp()
            } else {
                0.0
            };
            
            // Field Direction: Points Right (N->P).
            // Force = qE.
            let force_x = carrier.charge * field_strength; // +1 * E -> Right. -1 * E -> Left.
            
            // Update Position
            carrier.position.x += force_x;
            
            // Add some random thermal noise (Diffusion)
            let noise = (rand::rng().random::<f64>() - 0.5) * 0.5;
            carrier.position.x += noise;

            // Draw
            visualizer.draw_carrier(carrier.position.x, carrier.position.y, carrier.kind == FieldType::Hole);

            // Collection (Efficiency Metric)
            // Electron collected at Left (x < 200)
            // Hole collected at Right (x > 600)
            if carrier.kind == FieldType::FreeElectron && carrier.position.x <= 200.0 {
                carrier.active = false; // Harvested!
            } else if carrier.kind == FieldType::Hole && carrier.position.x >= 600.0 {
                carrier.active = false; // Harvested!
            }
        }
    }

    println!("Simulation Complete.");
    visualizer.save("simulation_output.png");
    println!("Saved visual to 'simulation_output.png'");

    // Benchmark logic remains same for photon attenuation
    // ... (omitted for brevity, code logic is identical to before)
}