[package]
name = "genetic_logic_shapes"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
image = "0.24"
rayon = "1.8" # For parallelizing the population evaluation
indicatif = "0.17" # For progress bars
imageproc = "0.23"
rusttype = "0.9"
clap = { version = "4.5.53", features = ["derive"] }
rand_chacha = "0.3"
wgpu = "0.19"
pollster = "0.4.0"
bytemuck = { version = "1.24.0", features = ["derive"] }
